version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"    # API
      - "9001:9001"    # UI
    environment:
      MINIO_ROOT_USER: "minio_user"
      MINIO_ROOT_PASSWORD: "minio_password"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    ports:
      - "9092:9092"

volumes:
  minio_data:
    driver: local